### ISSUE TITLE
require.paths is removed

### ISSUE THREAD

**Issue by TheCodeBuccaneer** [akdubya/dustjs#47]
When I try to include dust using dust = require('dust'), I get the following messageL

Error: require.paths is removed. Use node_modules folders, or the NODE_PATH environment variable instead.

How can I solve this error?

I am using version 0.6.7 of Node and the platform is Windows.

**Comment by TheCodeBuccaneer** [comment]
I saw this was already solved, sorry for that.

**Comment by hallettj** [comment]
How was this solved?  I am having the same problem.

**Comment by wendelicious** [comment]
When I npm install node, I get version 0.3.0, which seems to still have this issue.  How can I get version 0.6.0 ?
